### ISSUE TITLE
uninitialized constant Rack::TwilioWebhookAuthentication

### ISSUE THREAD

**Issue by samjbmason** [twilio/twilio-ruby#134]
I am using the gem and trying to initiate the Webhook Authentication inside `config/environments/development.rb` but I keep getting this error `NameError: uninitialized constant Rack::TwilioWebhookAuthentication`.

Here is the stacktrace:
```
~/Sites/buzzbot/config/environments/development.rb:4:in `block in <top (required)>'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/railtie.rb:210:in `instance_eval'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/railtie.rb:210:in `configure'
~/Sites/buzzbot/config/environments/development.rb:1:in `<top (required)>'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/engine.rb:597:in `each'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/engine.rb:597:in `block in <class:Engine>'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `call'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
~/Sites/buzzbot/config/environment.rb:5:in `<top (required)>'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
~/Sites/buzzbot/config.ru:3:in `block in <main>'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/builder.rb:4:in `instance_eval'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/builder.rb:4:in `initialize'
~/Sites/buzzbot/config.ru:1:in `new'
~/Sites/buzzbot/config.ru:1:in `<main>'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:51:in `eval'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:51:in `load_config'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:42:in `initialize'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:12:in `new'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:12:in `run'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/bin/nack_worker:4:in `<main>'
```

**Comment by philnash** [comment]
Hey Sam, what version of the gem are you using? The middleware was only introduced in version 3.12.0.

**Comment by samjbmason** [comment]
Hey Phil,
Strage as I only started the project last week, I assumed i had the latest version of the gem but it seems like I was running an old version `twilio-ruby (3.11.6)`.

Anyway, I have update the gems and restarted the app and Im still getting the same error.
```
NameError: uninitialized constant Rack::TwilioWebhookAuthentication
~/Sites/buzzbot/config/environments/development.rb:42:in `block in <top (required)>'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/railtie.rb:210:in `instance_eval'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/railtie.rb:210:in `configure'
~/Sites/buzzbot/config/environments/development.rb:1:in `<top (required)>'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/engine.rb:597:in `each'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/engine.rb:597:in `block in <class:Engine>'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `call'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
~/Sites/buzzbot/vendor/bundle/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
~/Sites/buzzbot/config/environment.rb:5:in `<top (required)>'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
~/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
~/Sites/buzzbot/config.ru:3:in `block in <main>'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/builder.rb:4:in `instance_eval'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/builder.rb:4:in `initialize'
~/Sites/buzzbot/config.ru:1:in `new'
~/Sites/buzzbot/config.ru:1:in `<main>'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:51:in `eval'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:51:in `load_config'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:42:in `initialize'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:12:in `new'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:12:in `run'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/bin/nack_worker:4:in `<main>'
```

**Comment by philnash** [comment]
Is there some gem that is holding back the version of `twilio-ruby` and keeping you pre-3.12.0? What's your `Gemfile.lock` saying right now?

**Comment by samjbmason** [comment]
Hey Phil,
You are totally right, it looks like im being held back at 3.11.6. The only gem I could imagine it being is `twiml_template` maybe?

**Comment by samjbmason** [comment]
All fixed, just forced an update, thanks for your help
