### ISSUE TITLE
Not handling HTTP 400 errors correctly

### ISSUE THREAD

**Issue by colby-swandale** [twilio/twilio-ruby#220]
Hi, I am trying to do some integration tests with the `twilio-ruby` gem and have come across a problem when i return a `HTTP 400 Bad Request` status response.

I am stubbing the request to the `phone_numbers` API using rspec which appears to be breaking the gem. The issue appears to be the [parser expects](https://github.com/twilio/twilio-ruby/blob/master/lib/twilio-ruby/rest/instance_resource.rb#L77) an empty hash to loop over but is instead being passed nil in this case (See failing spec)

```
begin
  lookup_client = Twilio::REST::LookupsClient.new Twilio.account_sid, Twilio.auth_token
  phone_lookup = lookup_client.phone_numbers.get full_phone_number

  if phone_lookup.phone_number
     ...
  end
  rescue Twilio::REST::RequestError
    render ...
  rescue Twilio::REST::ServerError, Twilio::REST::RequestError => e
    ...
end
```

```
    context 'when twilio responds with 500' do 
      before { stub_request(:get, auth_url + "lookups.twilio.com/v1/PhoneNumbers/+61%200432937289").to_return(status: [500, 'Internal Server Error']) }
      it 'logs the warning in rollbar' do
        expect(Rollbar).to receive(:warning)
        get :start_verification, phone_number: "0432937289"
      end
    end

    context 'when twilio responds with 400' do
      before { stub_request(:get, auth_url + "lookups.twilio.com/v1/PhoneNumbers/+61%200432937289").to_return(stauts: [400, 'Bad Request']) }
      it 'logs the error in rollbar' do
        expect(Rollbar).to receive(:error)
        get :start_verification, phone_number: "0432937289"
      end
    end
```

```
Run options: include {:locations=>{"./spec/controllers/phone_numbers_controller_spec.rb"=>[68]}}
F

Failures:

  1) PhoneNumbersController start_verification when twilio responds with 400 logs the error in rollbar
     Failure/Error: if phone_lookup.phone_number # Twilio wont call the API until you reference an attribute

     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./app/controllers/phone_numbers_controller.rb:23:in `start_verification'
     # ./lib/patches/actioncontroller_instrumentation.rb:18:in `block in process_action'
     # ./lib/patches/actioncontroller_instrumentation.rb:17:in `process_action'
     # ./spec/controllers/phone_numbers_controller_spec.rb:71:in `block (4 levels) in <top (required)>'
     # ./spec/support/spec_timer.rb:25:in `time'
     # ./spec/support/spec_timer.rb:64:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'

Finished in 0.89716 seconds (files took 44 minutes 15 seconds to load)
1 example, 1 failure
```

Version: 4.11.1

**Comment by colby-swandale** [comment]
i have just realised there is a typo in my code causing this issue, my apologies.
