### ISSUE TITLE
load such file -- libxml_ruby (LoadError) while running server

### ISSUE THREAD

**Issue by tpal94** [twilio/twilio-ruby#322]
```
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- libxml_ruby (LoadError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libxml-ruby-3.0.0-x64-mingw32/lib/libxml.rb:8:in `rescue in <top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libxml-ruby-3.0.0-x64-mingw32/lib/libxml.rb:4:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twilio-ruby-5.0.0/lib/twilio-ruby.rb:3:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:82:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `block in require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler.rb:108:in `require'
        from D:/projects/diasparkrwWEB5/config/application.rb:7:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:79:in `require'

        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:79:in `block in server'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:76:in `tap'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:76:in `server'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.1.12/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

I am facing the problem while running the application I have installed the lib-xml gem and using the rails 4.1.2 version.Please help what's wrong with it.

**Comment by jingming** [comment]
@tpal94 please redirect this question to help@twilio.com.
