### ISSUE TITLE
Uninitialized constant Rack::TwilioWebhookAuthentication (NameError)

### ISSUE THREAD

**Issue by kevgrig** [twilio/twilio-ruby#351]
**Version:** >= 5.3.0

### Code Snippet
```ruby
config.middleware.use(Rack::TwilioWebhookAuthentication, ENV["TWILIO_AUTH"], "/api/twilio")
```

### Exception/Log
```
[ 2017-10-10 03:11:06.7728 4274/7ff6b842f700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/www/html/[...]: An error occured while starting the web application.
  Error ID: 3180d9c8
  Error details saved to: /tmp/passenger-error-atNxms.html
  Message from application: uninitialized constant Rack::TwilioWebhookAuthentication (NameError)
  /var/www/html/[...]/config/application.rb:235:in `<class:Application>'
  /var/www/html/[...]/config/application.rb:140:in `<module:[...]>'
  /var/www/html/[...]/config/application.rb:16:in `<top (required)>'
  /var/www/html/[...]/config/environment.rb:2:in `require_relative'
  /var/www/html/[...]/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/www/html/[...]/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
  /var/www/html/[...]/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-loader.rb:106:in `eval'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-loader.rb:106:in `load_app'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-loader.rb:125:in `<module:App>'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-loader.rb:28:in `<module:PhusionPassenger>'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-loader.rb:27:in `<main>'
```

### Steps to Reproduce
1. Upgrade to >= 5.3.0

### Comments
It seems that `Rack::TwilioWebhookAuthentication` was removed in [5.3.0](https://github.com/twilio/twilio-ruby/commit/038a3f921bb6ae66063389d9f685ab297042d06a#diff-029220a2459bc061c22743334a7fbf0f). Was this an oversight or is it recommended that we implement our own? The [Twilio website](https://www.twilio.com/docs/guides/how-to-secure-your-sinatra-app-by-validating-incoming-twilio-requests) still references its usage.

### Workaround
```
gem "twilio-ruby", "~> 5.2.3"
```

**Comment by efossier** [comment]
@kevgrig Sorry for the confusion, this was an oversight and a bit hasty on our part. After talking it over with the team and seeing the response here on github we decided to restore those files in the next release. Thanks for your patience!
