### ISSUE TITLE
bad URI(absolute but no path): api.twilio.com://

### ISSUE THREAD

**Issue by lowki93** [twilio/twilio-ruby#356]
Hi, 

I would like to add a particapant in a conference with : 
```
client = Twilio::REST::Client.new(account_sid, api_secret)
client.api.conferences('conferenceNamz')
      .participants
      .create(
        from: '+33633333333',
        to: "client:#{@identity}",
     )
```

but i have this error : 
```
URI::InvalidURIError: bad URI(absolute but no path): api.twilio.com://
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/2.1.0/uri/common.rb:146:in `split'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/faraday-0.13.1/lib/faraday/connection.rb:453:in `proxy_from_env'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/faraday-0.13.1/lib/faraday/connection.rb:85:in `initialize'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/faraday-0.13.1/lib/faraday.rb:67:in `new'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/faraday-0.13.1/lib/faraday.rb:67:in `new'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/twilio-ruby-5.4.0/lib/twilio-ruby/http/http_client.rb:21:in `_request'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/twilio-ruby-5.4.0/lib/twilio-ruby/http/http_client.rb:54:in `request'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/twilio-ruby-5.4.0/lib/twilio-ruby/rest/client.rb:71:in `request'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/twilio-ruby-5.4.0/lib/twilio-ruby/framework/domain.rb:20:in `request'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/twilio-ruby-5.4.0/lib/twilio-ruby/framework/version.rb:51:in `request'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/twilio-ruby-5.4.0/lib/twilio-ruby/framework/version.rb:154:in `create'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/twilio-ruby-5.4.0/lib/twilio-ruby/rest/api/v2010/account/conference/participant.rb:103:in `create'
        from /Users/lowki93/workspace/Twilio/twilio-server/app/models/twilio_client.rb:61:in `invite'
        from (irb):8
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-4.1.16/lib/rails/commands/console.rb:90:in `start'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-4.1.16/lib/rails/commands/console.rb:9:in `start'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-4.1.16/lib/rails/commands/commands_tasks.rb:69:in `console'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-4.1.16/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /Users/lowki93/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-4.1.16/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'
```

**Comment by efossier** [comment]
@lowki93 We've got someone looking into this and they should get back to you in the next few days. In the meantime I was unable to reproduce fwiw:

```
irb(main):006:0> client.api.conferences('conferenceNamz').participants.create(from: '+33633333333',to: "client:#{identity}",)
Twilio::REST::RestError: [HTTP 403] 20006 : Unable to create record: Access Denied
	from /Users/efossier/Code/twilio/librarian/twilio-ruby/lib/twilio-ruby/framework/version.rb:157:in `create'
	from /Users/efossier/Code/twilio/librarian/twilio-ruby/lib/twilio-ruby/rest/api/v2010/account/conference/participant.rb:102:in `create'
	from (irb):6
	from /Users/efossier/.rbenv/versions/2.1.0/bin/irb:11:in `<main>'
```

My call actually made it to the API whereas yours seems to have blown up before making the request.

**Comment by jorgeliecer** [comment]
I have the same issue

**Comment by jurowski** [comment]
me as well

**Comment by Wylan** [comment]
We're having the same issue as well.

**Comment by Wylan** [comment]
Incase it helps I suspect this may be related to ruby versions. 

This issue appears in our application with ruby 2.1, twilio-ruby 5.4.2, & faraday 0.13.1 

Reverting to faraday 0.12.2 seems to resolve the issue in this project.

We have another project running the same version of twilio-ruby and faraday (0.13.1) on ruby 2.4 that doesn't experience the issue.

**Comment by alexcchan** [comment]
including the `https://` in the `url` to `Faraday.new` seems to make 0.13.1 happy (as the original error message hinted).

```
        @connection = Faraday.new(url: 'https://' + request.host + ':' + request.port.to_s, ssl: { verify: true }) do |f|
```

https://github.com/twilio/twilio-ruby/blob/25a8f9737d93f52a08b79c6cb7b097742d145184/lib/twilio-ruby/http/http_client.rb#L21
