### ISSUE TITLE
EOFError still cropping up... rest-client to blame?

### ISSUE THREAD

**Issue by matthooks** [twilio/twilio-ruby#39]
Hey guys,

I've been getting a large number of EOF errors using twilio-ruby. Here's an example stack trace:

```
EOFError: end of file reached
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/openssl/buffering.rb:174:in `sysread_nonblock'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/openssl/buffering.rb:174:in `read_nonblock'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/protocol.rb:153:in `rbuf_fill'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:1405:in `block in transport_request'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:1402:in `catch'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:1402:in `transport_request'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:1375:in `request'
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:1368:in `block in request'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:851:in `start'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:1366:in `request'
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
/app/vendor/bundle/ruby/2.0.0/gems/twilio-ruby-3.9.0/lib/twilio-ruby/rest/client.rb:213:in `connect_and_send'
/app/vendor/bundle/ruby/2.0.0/gems/twilio-ruby-3.9.0/lib/twilio-ruby/rest/client.rb:165:in `block (2 levels) in '
/app/vendor/bundle/ruby/2.0.0/gems/twilio-ruby-3.9.0/lib/twilio-ruby/rest/list_resource.rb:82:in `create'
/app/lib/twilio_interface.rb:25:in `call'
```

twilio_interface.rb is just a thin wrapper for the twilio-ruby gem.

```
class TwilioInterface
  def self.sms(to, body)
    options = {
      from: TWILIO_NUMBER,
      to: to,
      body: body
    }

    message = TWILIO.account.sms.messages.create(options)
    response = TwilioResponse.new(:success, message)

  rescue Twilio::REST::RequestError => e
    Airbrake.notify(e)
    response = TwilioResponse.new(:error, e)
  end

  def self.call(to, url)
    options = {
      format: 'json',
      from: TWILIO_NUMBER,
      to: to,
      url: url
    }

    call = TWILIO.account.calls.create(options)

    response = TwilioResponse.new(:success, call)
  rescue Twilio::REST::RequestError => e
    Airbrake.notify(e)
    response = TwilioResponse.new(:error, e)
  end
end
```

The calls to TwilioInterface are all made in Sidekiq background workers.

The issue I'm having is that the actual HTTP actions are taking place and calls/texts are completing, but the exceptions that are raised are causing my workers to be retried so I get duplicate calls/texts.

I'm going through today and making my workers idempotent, but any thought as to the root cause of these exceptions would be appreciated.

Theories:
- rest-client isn't thread-safe, which conflicts with sidekiq.
- Timeout?

**Comment by vijaychouhan-rails** [comment]
@invisiblefunnel, code  https://github.com/codeforamerica/citygram/commit/e97dcbb8a39a02100f008b17fc052b149ebdabb2 is working fine
