### ISSUE TITLE
Messaging Service Preventing Updates unless the `friendly_name` property is included in the update hash

### ISSUE THREAD

**Issue by jedschneider** [twilio/twilio-ruby#431]
I ran into this today while trying to write a small configuration script. 

* Message Service Update *fails* when I update only the setting I need

* Message Service Update *succeeds* when I update the setting I need AND the friendly name

**Version:** 5.15.2

### Code Snippet
```ruby
require 'twilio-ruby'
require 'yaml'
credentials = YAML.load(File.read('twilio.yml'))["development"]
client = Twilio::REST::Client.new(credentials["account_sid"], credentials["auth_token"])

service_id = credentials["service_id"]
service = client.messaging
  .services(service_id)
  .fetch

# validating the friendly name is set
puts "service friendly name: #{service.friendly_name}"

# FAILS when I update only the setting I need
updated_service = client.messaging
  .services(service_id)
  .update(status_callback: "https://yahoo.com")
puts "updated_service: #{updated_service.inspect}"

# SUCCEEDS when I also include the option, even though it is already set
updated_service = client.messaging
  .services(service_id)
  .update(friendly_name: service.friendly_name, status_callback: "https://yahoo.com")
puts "updated_service: #{updated_service.inspect}"
```

### Exception/Log
```
% ruby small_example.rb
service friendly name: pea-dev-message-service
Traceback (most recent call last):
	2: from small_example.rb:15:in `<main>'
	1: from /Users/jed/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/twilio-ruby-5.15.2/lib/twilio-ruby/rest/messaging/v1/service.rb:275:in `update'
/Users/jed/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/twilio-ruby-5.15.2/lib/twilio-ruby/framework/version.rb:90:in `update': [HTTP 400] 20002 : Unable to update record (Twilio::REST::RestError)
Friendly Name is empty
https://www.twilio.com/docs/errors/20002
```
### Success log
```
% ruby small_example.rb
service friendly name: pea-dev-message-service
updated_service: <Twilio.Messaging.V1.ServiceInstance <details redacted>>
```

### Steps to Reproduce
1. create a messaging service
2. attempt to update the service properties without providing a `friendly name` parameter

**Comment by childish-sambino** [comment]
Looks like this was fixed on the backend at some point as I'm not currently able to recreate the issue. Running the failure scenario mentioned is successful and updates the status callback properly.
