### ISSUE TITLE
uninitialized constant Faraday::Request::Authorization::KEY

### ISSUE THREAD

**Issue by JanOwiesniak** [twilio/twilio-ruby#448]
**Version: 5.22.0**

### Code Snippet
```ruby
require "twilio-ruby"

# Define Identity
identity = "random username"

# Create Chat Grant for Access Token
grant = Twilio::JWT::AccessToken::ChatGrant.new
grant.service_sid = ENV["TWILIO_CHAT_SERVICE_SID"]

# Create Access Token
token = Twilio::JWT::AccessToken.new(
  ENV["TWILIO_ACCOUNT_SID"],
  ENV["TWILIO_API_KEY"],
  ENV["TWILIO_API_SECRET"],
  [grant],
  identity: identity,
)

# Create Client
@client = Twilio::REST::Client.new(ENV["TWILIO_ACCOUNT_SID"], token)

# Create Channels
channels = @client.chat.services(ENV["TWILIO_CHAT_SERVICE_SID"]).channels

# List All Channels
channels.list # request crashes here
```

### Exception

```
uninitialized constant Faraday::Request::Authorization::KEY
```

### Stacktrace

```
bootsnap (1.3.1) lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
faraday (0.15.4) lib/faraday/connection.rb:444:in `set_authorization_header'
faraday (0.15.4) lib/faraday/connection.rb:194:in `basic_auth'
twilio-ruby (5.22.0) lib/twilio-ruby/http/http_client.rb:28:in `block in _request'
faraday (0.15.4) lib/faraday/connection.rb:89:in `initialize'
faraday (0.15.4) lib/faraday.rb:70:in `new'
faraday (0.15.4) lib/faraday.rb:70:in `new'
twilio-ruby (5.22.0) lib/twilio-ruby/http/http_client.rb:23:in `_request'
twilio-ruby (5.22.0) lib/twilio-ruby/http/http_client.rb:56:in `request'
twilio-ruby (5.22.0) lib/twilio-ruby/rest/client.rb:80:in `request'
twilio-ruby (5.22.0) lib/twilio-ruby/framework/domain.rb:22:in `request'
twilio-ruby (5.22.0) lib/twilio-ruby/framework/version.rb:53:in `request'
twilio-ruby (5.22.0) lib/twilio-ruby/framework/version.rb:131:in `page'
twilio-ruby (5.22.0) lib/twilio-ruby/rest/chat/v2/service/channel.rb:144:in `page'
twilio-ruby (5.22.0) lib/twilio-ruby/rest/chat/v2/service/channel.rb:109:in `stream'
twilio-ruby (5.22.0) lib/twilio-ruby/rest/chat/v2/service/channel.rb:90:in `list'
app/controllers/messengers_controller.rb:13:in `show'
```

### Steps to Reproduce

1. Create a new Twilio::REST::Client
2. Ask for all Chat Channels

**Comment by JanOwiesniak** [comment]
Just to let you know: This curl command is working as expected.

```
curl -X GET 'https://chat.twilio.com/v2/Services/TWILIO_CHAT_SERVICE_SID/Channels' -u TWILIO_ACCOUNT_SID:TWILIO_AUTH_TOKEN
```

**Comment by JanOwiesniak** [comment]
I defined a constant called `KEY` in my global namespace which confused faraday. You can read more about this issue [here](https://github.com/lostisland/faraday/issues/974).
