### ISSUE TITLE
minor version update is not backward compatible

### ISSUE THREAD

**Issue by slayer** [twilio/twilio-ruby#454]
**Version:**
Update version:
```
-    twilio-ruby (5.10.3)
+    twilio-ruby (5.24.0)
```

### Code Snippet
```ruby
  def some_action
    ...
    xml = Twilio::TwiML::VoiceResponse.new do |voice_response|
      voice_response.say 'Hello.', say_params
    end
    ...
  end
```

### Exception/Log
```
  1) TwilioController POST#some_action action should be rendering xml
     Failure/Error: voice_response.say 'Hello.', say_params

     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./app/controllers/twilio_controller.rb:26:in `block in some_action'
     # ./app/controllers/twilio_controller.rb:25:in `new'
```

### Steps to Reproduce
1. Update gem from 5.10.3 to 5.24.0

**Comment by childish-sambino** [comment]
The Twilio helper libraries follow a modified semver strategy: https://github.com/twilio/twilio-ruby/blob/master/VERSIONS.md
Backwards-incompatible changes may show up in minor version rolls.
