### ISSUE TITLE
wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by monelgordillo** [twilio/twilio-ruby#567]
### Issue Summary
This issue cropped up after updating Twilio ruby gem.

I'm getting "wrong number of arguments (given 1, expected 0)".  See error log for details.  Thank you.

### Steps to Reproduce
1. return render_twilio_sms('Thanks for checking in!', phone, kitestring_phone, user)
2. def render_twilio_sms(message, to, from, user)
3. Then, error message "wrong number of arguments (given 1, expected 0)"

### Code Snippet
Snippet of home_controller.rb (line #975 starts at r.message(message):
```ruby
  # render an SMS response to twilio
  def render_twilio_sms(message, to, from, user)
    TextMessage.create!(
      :to => to,
      :from => from,
      :body => message,
      :twilio_sid => nil,
      :user_id => user.try(:id),
      :outgoing => true
    )

    # uninitialized constant Twilio::TwiML::Response
    # https://stackoverflow.com/questions/48410712/nameerror-uninitialized-constant-twiliotwimlresponse-possibly-from-old-ap
    #twiml = Twilio::TwiML::Response.new do |r|
    twiml = Twilio::TwiML::MessagingResponse.new do |r|
      #r.Message(message)
      r.message(message)
    end
    return render :xml => twiml.text
  end

```

### Exception/Log
```
021-08-17T19:20:33.380224+00:00 app[web.1]: 19:20:33 web.1   | Message: wrong number of arguments (given 1, expected 0)
2021-08-17T19:20:33.380291+00:00 app[web.1]: 19:20:33 web.1   | Stack trace:
2021-08-17T19:20:33.380371+00:00 app[web.1]: 19:20:33 web.1   |
2021-08-17T19:20:33.380441+00:00 app[web.1]: 19:20:33 web.1   | /app/vendor/bundle/ruby/2.5.0/gems/twilio-ruby-5.58.0/lib/twilio-ruby/twiml/messaging_response.rb:30:in `message'
2021-08-17T19:20:33.380509+00:00 app[web.1]: 19:20:33 web.1   | /app/app/controllers/home_controller.rb:975:in `block in render_twilio_sms'
2021-08-17T19:20:33.380588+00:00 app[web.1]: 19:20:33 web.1   | /app/vendor/bundle/ruby/2.5.0/gems/twilio-ruby-5.58.0/lib/twilio-ruby/twiml/messaging_response.rb:18:in `initialize'
2021-08-17T19:20:33.380657+00:00 app[web.1]: 19:20:33 web.1   | /app/app/controllers/home_controller.rb:973:in `new'
2021-08-17T19:20:33.380742+00:00 app[web.1]: 19:20:33 web.1   | /app/app/controllers/home_controller.rb:973:in `render_twilio_sms'
2021-08-17T19:20:33.380806+00:00 app[web.1]: 19:20:33 web.1   | /app/app/controllers/home_controller.rb:362:in `block in twilio_sms'
2021-08-17T19:20:33.380865+00:00 app[web.1]: 19:20:33 web.1   | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3/lib/active_record/locking/pessimistic.rb:88:in `block in with_lock'
```

### Technical details:
* twilio-ruby version: 5.58.0
* ruby version: 2.5.9p229

**Comment by shwetha-manvinkurke** [comment]
Try replacing `r.message(message)` with `r.message(body: message)`

**Comment by monelgordillo** [comment]
> r.message(body: message)

I tried it.  I'm getting something different now:

`2021-08-17T21:24:45.720325+00:00 app[web.1]: 21:24:45 web.1   | Message: undefined method `text' for #<Twilio::TwiML::MessagingResponse:0x00005600e7d45858>
2021-08-17T21:24:45.720372+00:00 app[web.1]: 21:24:45 web.1   | Stack trace:
2021-08-17T21:24:45.720417+00:00 app[web.1]: 21:24:45 web.1   |
2021-08-17T21:24:45.720452+00:00 app[web.1]: 21:24:45 web.1   | /app/app/controllers/home_controller.rb:979:in `render_twilio_sms'
2021-08-17T21:24:45.720527+00:00 app[web.1]: 21:24:45 web.1   | /app/app/controllers/home_controller.rb:421:in `block in twilio_sms'
2021-08-17T21:24:45.720577+00:00 app[web.1]: 21:24:45 web.1   | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3/lib/active_record/locking/pessimistic.rb:88:in `block in with_lock'
2021-08-17T21:24:45.720612+00:00 app[web.1]: 21:24:45 web.1   | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
2021-08-17T21:24:45.720649+00:00 app[web.1]: 21:24:45 web.1   | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:310:in `block in within_new_transaction'
2021-08-17T21:24:45.720704+00:00 app[web.1]: 21:24:45 web.1   | /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize`

**Comment by shwetha-manvinkurke** [comment]
[TwiML](https://github.com/twilio/twilio-ruby/blob/main/lib/twilio-ruby/twiml/twiml.rb#L29) doesn't have a method called `text`.

**Comment by monelgordillo** [comment]
I figured it out from here: https://github.com/twilio/twilio-ruby/issues/314

Had to use to_s
