### ISSUE TITLE
Unable to POST to `tollfree_verifications.create` - getting missing parameter even though it is included

### ISSUE THREAD

**Issue by dodontommy** [twilio/twilio-ruby#674]
### Issue Summary
When trying to submit a `tollfree_verification` through the Ruby SDK, I get `Missing required parameter *param* in the post body` for any array params, so for `OptInImageUrls` and `UseCaseCategories`, even though those params are included and are of type `Array`. 

### Steps to Reproduce
1. Call `client.messaging.v1.tollfree_verifications.create(params)`

### Code Snippet
```ruby
USE_CASE_SUMMARY = 'Foo bar'
    PRODUCTION_MESSAGE_SAMPLE_1 = "EXAMPLE 1 STOP TO OPT OUT"
    PRODUCTION_MESSAGE_SAMPLE_2 = "EXAMPLE 2 STOP TO OPT OUT"
    OPT_IN_IMAGE_URLS = ['valid_image_url, 'valid_image_url_2, 'valid_image_url_3'].freeze
sub_account_client.messaging.v1.tollfree_verifications.create(business_street_address: verification_params[:street],
        business_street_address2: verification_params[:street_2],
        business_city: verification_params[:city],
        business_state_province_region: verification_params[:state],
        business_postal_code: verification_params[:zip_code],
        business_country: verification_params[:country],
        business_contact_first_name: verification_params[:first_name],
        business_contact_last_name: verification_params[:last_name],
        business_contact_email: verification_params[:email],
        business_contact_phone: verification_params[:phone_number],
        additional_information: verification_params[:additional_information],
        business_name: verification_params[:business_name],
        business_website: verification_params[:business_website],
        notification_email: 'it@foo.net',
        use_case_categories: ['ACCOUNT_NOTIFICATIONS','EVENTS'],
        use_case_summary: USE_CASE_SUMMARY,
        production_message_sample: [PRODUCTION_MESSAGE_SAMPLE_1, PRODUCTION_MESSAGE_SAMPLE_2].join('; '),
        opt_in_image_urls: OPT_IN_IMAGE_URLS,
        opt_in_type: 'WEB_FORM',
        message_volume: '1,000',
        tollfree_phone_number_sid: phone_number_sid)
```
### Exception/Log
```
/app/vendor/bundle/ruby/2.7.0/gems/twilio-ruby-6.5.0/lib/twilio-ruby/framework/rest/version.rb:146:in `create': [HTTP 400] 20001 : Unable to create record (Twilio::REST::RestError)
Missing required parameter OptInImageUrls in the post body
https://www.twilio.com/docs/errors/20001
```

Or when just sending a single string for OptInImageUrls: 
```
/app/vendor/bundle/ruby/2.7.0/gems/twilio-ruby-6.5.0/lib/twilio-ruby/framework/rest/version.rb:146:in `create': [HTTP 400] 20001 : Unable to create record (Twilio::REST::RestError)
Missing required parameter UseCaseCategories in the post body
https://www.twilio.com/docs/errors/20001
```

### Technical details:
* twilio-ruby version: `6.5.0`
* ruby version: `2.7.2`

**Comment by dodontommy** [comment]
This seems to be because we are attempting to hit the tollfree verification API using a subaccount.

**Comment by willdebernardi** [comment]
Did you ever find a fix for this? I am getting the same error but for the "BusinessCity" parameter instead.
